name: "Docker Builds"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use jojees/dockertest
      uses: ./
      with:
        exec: |
          wget https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb && \
          sudo dpkg -i vagrant_2.2.14_x86_64.deb && \
          docker build -f Dockerfile -t jojees/dockertest:0.1