name: "Docker Builds"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code into workspace directory
      uses: actions/checkout@v2

    - name: Setup Vagrant
      run: |
        wget https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
        sudo dpkg -i vagrant_2.2.14_x86_64.deb
        docker build -f Dockerfile -t jojees/dockertest:0.1 .