name: "Docker Builds"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code into workspace directory
      uses: actions/checkout@v2

    - name: List directory
      run: ls -lRa